services:
  - type: web
    name: face-reco-ss
    runtime: docker
    plan: free
    envVars:
      - key: PORT
        value: 5001
      - key: WEB_CONCURRENCY
        value: 1
      - key: PYTHONUNBUFFERED
        value: 1
      - key: SECRET_KEY
        generateValue: true
